name: Build

run-name: >
  Build Java Lib —
  ${{ github.event_name }} (${{ github.head_ref || github.ref_name }}) —
  [${{ github.event_name == 'push' && format('{0}', github.event.head_commit.message) || '' }}
  ${{ github.event_name == 'pull_request' && format('{0}', github.event.pull_request.title) || '' }}]

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-java-lib:
    name: Build java lib
    uses: Netcracker/qubership-core-infra/.github/workflows/generic-build-maven-lib.yaml@v1.2.1
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
